import requests  # type: ignore
import json

# base_url = "https://iq.qa.app.neeve.ai/"
base_url = "https://iq-api.qa.app.neeve.ai"

end_point = "/api/v1/sites" 

url = base_url + end_point

token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImxvMzRfeXVrbm9JdllWVWFkS1dNRyJ9.eyJpc3MiOiJodHRwczovL2Rldi02bHlzb2lmemluYmsxdGVkLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiI3TWZoUGpicU9ZNjdidGVGamtPTEtOUUx3blRmWG5WNkBjbGllbnRzIiwiYXVkIjoiaXEucWEuYXBwLm5lZXZlLmFpIiwiaWF0IjoxNzM4MTU3NzM1LCJleHAiOjE3MzgyNDQxMzUsInNjb3BlIjoicmVhZDp1c2Vyc19hcHBfbWV0YWRhdGEgdXBkYXRlOnVzZXJzX2FwcF9tZXRhZGF0YSBkZWxldGU6dXNlcnNfYXBwX21ldGFkYXRhIGFpOnNvdF9tYXBwaW5nIGNyZWF0ZTp1c2VycyBkZWxldGU6dXNlcnMgcmVhZDp1c2VycyB1cGRhdGU6dXNlcnMgY3JlYXRlOnRlbmFudHMgcmVhZDp0ZW5hbnRzIGRlbGV0ZTp0ZW5hbnRzIGNyZWF0ZTpkYXRhc291cmNlIHJlYWQ6ZGF0YXNvdXJjZSBjcmVhdGU6b3JnYW5pemF0aW9uIGNyZWF0ZTpvcmdhbml6YXRpb25fbWVtYmVyX3JvbGVzIGNyZWF0ZTpvcmdhbml6YXRpb25fbWVtYmVycyBjcmVhdGU6dXNlcnNfYXBwX21ldGFkYXRhIGRlbGV0ZTpvcmdhbml6YXRpb24gZGVsZXRlOm9yZ2FuaXphdGlvbl9tZW1iZXJfcm9sZXMgZGVsZXRlOm9yZ2FuaXphdGlvbl9tZW1iZXJzIHJlYWQ6b3JnYW5pemF0aW9uIHJlYWQ6b3JnYW5pemF0aW9uX21lbWJlcl9yb2xlcyByZWFkOm9yZ2FuaXphdGlvbl9tZW1iZXJzIHVwZGF0ZTpvcmdhbml6YXRpb24gdXBkYXRlOm9yZ2FuaXphdGlvbl9tZW1iZXJfcm9sZXMgdXBkYXRlOm9yZ2FuaXphdGlvbl9tZW1iZXJzIHVwZGF0ZTpzaXRlIHVwZGF0ZTp0ZW5hbnRzIHJlYWQ6c2l0ZSBjcmVhdGU6c2l0ZSBkZWxldGU6c2l0ZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsImF6cCI6IjdNZmhQamJxT1k2N2J0ZUZqa09MS05RTHduVGZYblY2IiwicGVybWlzc2lvbnMiOlsicmVhZDp1c2Vyc19hcHBfbWV0YWRhdGEiLCJ1cGRhdGU6dXNlcnNfYXBwX21ldGFkYXRhIiwiZGVsZXRlOnVzZXJzX2FwcF9tZXRhZGF0YSIsImFpOnNvdF9tYXBwaW5nIiwiY3JlYXRlOnVzZXJzIiwiZGVsZXRlOnVzZXJzIiwicmVhZDp1c2VycyIsInVwZGF0ZTp1c2VycyIsImNyZWF0ZTp0ZW5hbnRzIiwicmVhZDp0ZW5hbnRzIiwiZGVsZXRlOnRlbmFudHMiLCJjcmVhdGU6ZGF0YXNvdXJjZSIsInJlYWQ6ZGF0YXNvdXJjZSIsImNyZWF0ZTpvcmdhbml6YXRpb24iLCJjcmVhdGU6b3JnYW5pemF0aW9uX21lbWJlcl9yb2xlcyIsImNyZWF0ZTpvcmdhbml6YXRpb25fbWVtYmVycyIsImNyZWF0ZTp1c2Vyc19hcHBfbWV0YWRhdGEiLCJkZWxldGU6b3JnYW5pemF0aW9uIiwiZGVsZXRlOm9yZ2FuaXphdGlvbl9tZW1iZXJfcm9sZXMiLCJkZWxldGU6b3JnYW5pemF0aW9uX21lbWJlcnMiLCJyZWFkOm9yZ2FuaXphdGlvbiIsInJlYWQ6b3JnYW5pemF0aW9uX21lbWJlcl9yb2xlcyIsInJlYWQ6b3JnYW5pemF0aW9uX21lbWJlcnMiLCJ1cGRhdGU6b3JnYW5pemF0aW9uIiwidXBkYXRlOm9yZ2FuaXphdGlvbl9tZW1iZXJfcm9sZXMiLCJ1cGRhdGU6b3JnYW5pemF0aW9uX21lbWJlcnMiLCJ1cGRhdGU6c2l0ZSIsInVwZGF0ZTp0ZW5hbnRzIiwicmVhZDpzaXRlIiwiY3JlYXRlOnNpdGUiLCJkZWxldGU6c2l0ZSJdfQ.wdeApWbvniZdlncBEoY-Jiq7ksouoRsgkwWN3AcBgl73Tl2ALkbdKxRyGb0FRwrrqGru28QnKtpeHWpqSBstLUMKcppauspJBwMuwXcUFqJC8Y61Tw4Kk_nmADmoHFaCfe2MxPdqscSimTcx3QtfOE_AjxA5pSlPSgyOLMpua8bTgyu418WR6zBd7n95jIA2i_zsZGl78wsUtG7aNrliTU0Pg1QpMUZ4EMm7tLd1B0SHMXwn9n4qgEVttzI33KV9enfqV_b7wUkgi-dF5_y5KMhZh_HY5g5jJRnrWGFvVhYyBjEhUqUDsmEtA3YWA3FOT3Gxza7iJ6EHtMe2AH4SCg"

headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json"
}

response = requests.get(url,headers=headers)
if response:
    json_data = response.json()
    print(json_data)
    
    # json_string = json.dumps(json_data)
    # print(json_string)
# # Print response status & JSON
# print("Status Code: ", response.status_code)
# print("response text :", response.text)
# # print("Response:", response.json())  # Convert response to JSON